// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBMuVN7EGT4zpQR0y2SWyMCFbW7FMH56IQ',
    appId: '1:310630132904:android:0244fa3886996d0e1c269d',
    messagingSenderId: '310630132904',
    projectId: 'up-event-44ee1',
    databaseURL: 'https://up-event-44ee1-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'up-event-44ee1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDNPA1f7Po2JcGAbwWTlRnlnr9gpN50VuE',
    appId: '1:310630132904:ios:05978d8e441035b51c269d',
    messagingSenderId: '310630132904',
    projectId: 'up-event-44ee1',
    databaseURL: 'https://up-event-44ee1-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'up-event-44ee1.appspot.com',
    androidClientId: '310630132904-bsi50bov4cbd4rik7jjptnn66663mgpl.apps.googleusercontent.com',
    iosClientId: '310630132904-0jj38eibn9rbcgfce80jov4avggc1m4u.apps.googleusercontent.com',
    iosBundleId: 'com.example.upeventadmin',
  );
}
